services:
  postgres:
    image: postgres:15-alpine
    container_name: container-postgres

    ## define variavel de ambiente
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER_ROOT}
      - POSTGRES_PASSWORD=${POSTGRES_PASS_ROOT}

    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  api:
    build: .
    container_name: container-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

    environment:

      - SPRING_DATASOURCE_URL=${DB_URL_INTERNAL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER_ROOT}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASS_ROOT}

      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
volumes:
  postgres-data: